{{- if .Values.dbt.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-runner
  namespace: {{ default "feedback" .Values.namespace | quote }}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dbt-runner
          image: "{{ .Values.dbt.image.repository }}:{{ .Values.dbt.image.tag }}"
          imagePullPolicy: {{ .Values.dbt.image.pullPolicy }}
          command: ["/bin/bash", "-lc"]
          args: ["dbt debug && dbt run && dbt test"]
          env:
            - { name: DBT_PROFILES_DIR, value: /app/analytics/dbt/fip_analytics }
            - { name: RDS_HOST, value: {{ .Values.dbt.rds.host | quote }} }
            - { name: RDS_PORT, value: {{ .Values.dbt.rds.port | quote }} }
            - { name: RDS_DB_NAME, value: {{ .Values.dbt.rds.dbName | quote }} }
            - { name: RDS_USERNAME, value: {{ .Values.dbt.rds.username | quote }} }
            - { name: RDS_PASSWORD, value: {{ .Values.dbt.rds.password | quote }} }
{{- end }}
