apiVersion: v1
kind: Service
metadata:
  name: {{ include "feedback-platform.apiName" . | quote }}
  namespace: {{ default "feedback" .Values.namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "feedback-platform.apiName" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "feedback-platform.apiName" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  ports:
    - name: http
      port: {{ default 80 .Values.api.servicePort }}
      targetPort: {{ default 80 .Values.api.containerPort }}